
#spring.application.name=microservice-course
server:
  port: 8091 #numero de puerto

spring:
  application:
    name: microservice-course
  config:
    import: optional:configserver:http://localhost:8888 # Conexion al config server
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root

  #CONFIGURATION TO SQL SERVER(FIX IT )
    #username: sa # sql server user
    #password: pachan242 # sql server password
    #url: jdbc:sqlserver://DESKTOP-B5HECAG:1433;databaseName=course_db;instanceName=sqlexpress
    #url: jdbc:sqlserver://DESKTOP-B5HECAG\SQLEXPRESS;databaseName=course_db;integratedSecurity=false;encrypt=false;trustServerCertificate=true # conexion al MICROSOFT SQL SERVER
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: pachan242
    url: jdbc:mysql://localhost:3306/course_db
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

